// app/layout.tsx
import type { Metadata } from "next";

import "./globals.css"; // Your main CSS file

export const metadata: Metadata = {
  title: "Shoe Me",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* Now using the Tailwind utility generated from --font-Primary */}
        <div className={`font-Primary antialiased`}>
          {children}
        </div>
      </body>
    </html>
  );
}